# Generated by Django 5.1.1 on 2024-10-16 09:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_email_verified_alter_user_is_active_and_more'),
        ('school', '0002_branch_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hire_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.school'),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
