# Generated by Django 4.2.7 on 2024-08-22 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_branch_user_id"),
        ("academics", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="department",
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program",
                        to="school.school",
                    ),
                ),
            ],
        ),
    ]
