# Generated by Django 4.2.7 on 2024-08-22 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_branch_user_id"),
        ("academics", "0003_remove_course_department_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="program",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="academics.program",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="school",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="program",
                to="school.school",
            ),
        ),
    ]
