# Generated by Django 4.2.7 on 2024-08-26 12:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_branch_user_id"),
        ("academics", "0004_course_program_alter_program_school"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(default="", max_length=255)),
                ("last_name", models.CharField(default="", max_length=255)),
                ("age", models.IntegerField(default=1)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        default="Male",
                        max_length=10,
                    ),
                ),
                (
                    "dob",
                    models.DateField(
                        default=datetime.timezone, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "pob",
                    models.CharField(
                        default="", max_length=255, verbose_name="Place of Birth"
                    ),
                ),
                ("nationality", models.CharField(default="", max_length=225)),
                (
                    "belt_level",
                    models.CharField(
                        default="", max_length=50, verbose_name="Belt Level"
                    ),
                ),
                ("phone", models.CharField(default="", max_length=255)),
                ("email", models.EmailField(default="", max_length=254)),
                (
                    "mother_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="Mother's Name"
                    ),
                ),
                (
                    "mother_occupation",
                    models.CharField(
                        default="", max_length=255, verbose_name="Mother's Occupation"
                    ),
                ),
                (
                    "father_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="Father's Name"
                    ),
                ),
                (
                    "father_occupation",
                    models.CharField(
                        default="", max_length=255, verbose_name="Father's Occupation"
                    ),
                ),
                ("address", models.CharField(default="", max_length=255)),
                (
                    "parent_contact",
                    models.CharField(
                        default="", max_length=255, verbose_name="Parent's Contact"
                    ),
                ),
                (
                    "student_passport",
                    models.CharField(
                        default="", max_length=255, verbose_name="Student Passport"
                    ),
                ),
                ("admission_date", models.DateField(default=datetime.timezone)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="school.branch",
                    ),
                ),
            ],
        ),
    ]
