# Generated by Django 4.2.7 on 2024-08-27 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academics", "0005_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("number_student", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "assign_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_recieved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "handle_by",
                    models.ManyToManyField(
                        related_name="user_handle", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "programs",
                    models.ManyToManyField(
                        related_name="program", to="academics.program"
                    ),
                ),
            ],
        ),
    ]
