# Generated by Django 5.1.1 on 2024-09-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_remove_classroom_course_classroom_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='students/images/'),
        ),
    ]
