# Generated by Django 5.1.1 on 2024-10-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_student_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classroom',
        ),
        migrations.AddField(
            model_name='student',
            name='classrooms',
            field=models.ManyToManyField(related_name='students', to='academics.classroom'),
        ),
    ]
