# Generated by Django 5.1.1 on 2024-09-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images/'),
        ),
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programs/images/'),
        ),
        migrations.AddField(
            model_name='trail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trails/images/'),
        ),
    ]
