# Generated by Django 5.1.1 on 2024-10-10 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_course_image_program_image_trail_image'),
        ('school', '0002_branch_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='school',
        ),
        migrations.AddField(
            model_name='program',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Branch', to='school.branch'),
        ),
    ]
