# Generated by Django 5.1.1 on 2024-11-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_alter_examresult_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='student',
            field=models.ManyToManyField(related_name='students_classroom', to='academics.student'),
        ),
    ]
