# Generated by Django 4.2.7 on 2024-08-29 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="roles",
        ),
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="authentication.userrole",
            ),
        ),
    ]
