# Generated by Django 4.2.7 on 2024-08-29 11:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_trail"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="courses",
            field=models.ManyToManyField(related_name="courses", to="academics.course"),
        ),
        migrations.AddField(
            model_name="student",
            name="courses",
            field=models.ManyToManyField(
                related_name="students", to="academics.course"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academics.program",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="academics.student",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="admission_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="student",
            name="dob",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date of Birth"
            ),
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="course",
        ),
    ]
