# Generated by Django 4.2.7 on 2024-08-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academics",
            "0007_alter_enrollment_unique_together_enrollment_courses_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroom",
            name="course",
        ),
        migrations.AddField(
            model_name="classroom",
            name="courses",
            field=models.ManyToManyField(
                related_name="courses_classroom", to="academics.course"
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="courses",
            field=models.ManyToManyField(
                related_name="courses_enrollment", to="academics.course"
            ),
        ),
    ]
